const services = [
  {
    name: "Pediatrics",
    desc: "Neque rhoncus ipsum tempor varius iaculis at luctus, neque rhoncus tempor varius cubilia Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit emper lacus",
    price: 145,
    duration: 23,
    imgDetails: "https://i.ibb.co/mhdpyhZ/Ottawa-BB.jpg",
    imgMain: "https://i.ibb.co/KwmfMh1/image-5.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra",
  },
  {
    name: "Hematology",
    desc: "Primis cubilia laoreet augue vitae laoreet augue in cubilia risus auctor tempus dolor feugiat, felis lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet quisque an aliquet. Feugiat primis in ultrice ligula risus auctor Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit . Fringilla risus nec, luctus mauris orci auctor purus euismod pretium purus pretium ligula rutrum tempor sapien at pretium luctus ligula rutrum luctus risus ultrice lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet Quaerat sodales sapien undo euismod purus a blandit pretium Nemo ipsam egestas volute turpis dolores ut aliquam quaerat sodales sapien undo pretium purus feugiat dolor impedit magna purus pretium gravida donec quisque an aliquet",
    price: 250,
    duration: 30,
    imgDetails: "https://i.ibb.co/sjvn1QL/Getty-Images-1183390789-hero-1024x575.webp",
    imgMain: "https://i.ibb.co/ZNtS4tL/hematology-700x700.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra cubilia laoreet augue",
  },
  {
    name: "MRI Diagnostic",
    desc: "Neque rhoncus ipsum tempor varius iaculis at luctus, neque rhoncus tempor varius cubilia Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit emper lacus",
    price: 145,
    duration: 23,
    imgDetails: "https://i.ibb.co/ZcpWTMH/mri-1000x500.jpg",
    imgMain: " https://i.ibb.co/NVZnNCy/mri-700x700.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra",
  },
  {
    name: "X-Ray Diagnostic",
    desc: "Primis cubilia laoreet augue vitae laoreet augue in cubilia risus auctor tempus dolor feugiat, felis lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet quisque an aliquet. Feugiat primis in ultrice ligula risus auctor Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit . Fringilla risus nec, luctus mauris orci auctor purus euismod pretium purus pretium ligula rutrum tempor sapien at pretium luctus ligula rutrum luctus risus ultrice lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet Quaerat sodales sapien undo euismod purus a blandit pretium Nemo ipsam egestas volute turpis dolores ut aliquam quaerat sodales sapien undo pretium purus feugiat dolor impedit magna purus pretium gravida donec quisque an aliquet",
    price: 250,
    duration: 39,
    imgDetails: "https://i.ibb.co/nDPNFm4/Siemens-Healthcare-Artis-Zeego-Medizinroboter-3.jpg",
    imgMain: "https://i.ibb.co/TrJgyC6/x-ray-700x700.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra cubilia laoreet augue",
  },
  {
    name: "Echocardiography",
    desc: "Neque rhoncus ipsum tempor varius iaculis at luctus, neque rhoncus tempor varius cubilia Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit emper lacus",
    price: 345,
    duration: 45,
    imgDetails: "https://i.ibb.co/Nn0hkfy/istockphoto-1139755627-612x612.jpg",
    imgMain: "https://i.ibb.co/bmdNdC8/global-echocardiogram.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra",
  },
  {
    name: "CT & Ultrasound Diagnostic",
    desc: "Primis cubilia laoreet augue vitae laoreet augue in cubilia risus auctor tempus dolor feugiat, felis lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet quisque an aliquet. Feugiat primis in ultrice ligula risus auctor Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit . Fringilla risus nec, luctus mauris orci auctor purus euismod pretium purus pretium ligula rutrum tempor sapien at pretium luctus ligula rutrum luctus risus ultrice lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet Quaerat sodales sapien undo euismod purus a blandit pretium Nemo ipsam egestas volute turpis dolores ut aliquam quaerat sodales sapien undo pretium purus feugiat dolor impedit magna purus pretium gravida donec quisque an aliquet",
    price: 359,
    duration: 25,
    imgDetails: "https://i.ibb.co/ZYvCwrG/CT-Scan-cropped.jpg",
    imgMain: "https://i.ibb.co/mtjRCZJ/PHG-website-images-15.webp",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra cubilia laoreet augue",
  },
  {
    name: "	MRI & X-Ray",
    desc: "Neque rhoncus ipsum tempor varius iaculis at luctus, neque rhoncus tempor varius cubilia Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit emper lacus",
    price: 99,
    duration: 40,
    imgDetails: "https://i.ibb.co/Hrh7zLr/256-2018-3045-Fig1-HTML.png",
    imgMain: "https://i.ibb.co/k5qVRDp/ct-body.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra",
  },
  {
    name: "Full Blood Picture",
    desc: "Primis cubilia laoreet augue vitae laoreet augue in cubilia risus auctor tempus dolor feugiat, felis lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet quisque an aliquet. Feugiat primis in ultrice ligula risus auctor Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit . Fringilla risus nec, luctus mauris orci auctor purus euismod pretium purus pretium ligula rutrum tempor sapien at pretium luctus ligula rutrum luctus risus ultrice lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet Quaerat sodales sapien undo euismod purus a blandit pretium Nemo ipsam egestas volute turpis dolores ut aliquam quaerat sodales sapien undo pretium purus feugiat dolor impedit magna purus pretium gravida donec quisque an aliquet",
    price: 50,
    duration: 20,
    imgDetails: "https://i.ibb.co/J7V4bK2/ae9b49b8-2cb0-44f4-847e-a5dbfae52f4c-939x.webp",
    imgMain: "https://i.ibb.co/4gDxDxQ/Getty-Images-1183390789-hero-1024x575-1.webp",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra cubilia laoreet augue",
  },
  {
    name: "Bronchoscopy",
    desc: "Neque rhoncus ipsum tempor varius iaculis at luctus, neque rhoncus tempor varius cubilia Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit emper lacus",
    price: 133,
    duration: 15,
    imgDetails: "https://i.ibb.co/ZmRdvBH/bronchoscopy-190425071206-thumbnail-4.webp",
    imgMain: "https://i.ibb.co/d5KjpNP/maxresdefault.jpg",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra",
  },
  {
    name: "Parathyroid Scan",
    desc: "Primis cubilia laoreet augue vitae laoreet augue in cubilia risus auctor tempus dolor feugiat, felis lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet quisque an aliquet. Feugiat primis in ultrice ligula risus auctor Ligula risus auctor tempus dolor feugiat, felis lacinia risus interdum auctor id viverra dolor iaculis luctus bibendum luctus neque rhoncus ipsum tempor varius iaculis at luctus neque rhoncus ipsum tempor varius cubilia laoreet augue vitae laoreet augue undo cubilia feugiat suscipit . Fringilla risus nec, luctus mauris orci auctor purus euismod pretium purus pretium ligula rutrum tempor sapien at pretium luctus ligula rutrum luctus risus ultrice lacinia risus auctor id viverra dolor congue ipsum mauris iaculis luctus placerat massa magna cursus amet Quaerat sodales sapien undo euismod purus a blandit pretium Nemo ipsam egestas volute turpis dolores ut aliquam quaerat sodales sapien undo pretium purus feugiat dolor impedit magna purus pretium gravida donec quisque an aliquet",
    price: 499,
    duration: 50,
    imgDetails: "https://i.ibb.co/wBktWQV/parathyroid1-1080x675.jpg",
    imgMain: " https://i.ibb.co/mtjRCZJ/PHG-website-images-15.webp",
    category: "Maecenas gravida porttitor nunc, magna luctus tempor viverra cubilia laoreet augue",
  },
];
